version: 2.1

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: main

jobs:
  test:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      - run:
          name: Run SonarQube analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=${PROJECT_KEY} \
              -Dsonar.sources=. \
              -Dsonar.host.url=${SONAR_HOST_URL} \
              -Dsonar.login=${SONAR_TOKEN}