name: Ant Build with Ivy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Ant with Ivy
      run: |
        mkdir -p ~/.ant/lib lib
        # Download Ivy for dependency resolution
        wget -O ~/.ant/lib/ivy-2.5.2.jar https://repo1.maven.org/maven2/org/apache/ivy/ivy/2.5.2/ivy-2.5.2.jar

    - name: Run Ant build with dependency resolution
      run: ant -f antbuild.xml resolve clean build
      env:
        JAVA_HOME: ${{ env.JAVA_HOME }}
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          build/
          dist/
          lib/
        retention-days: 30