pipelines:
  default:
    - step:
        name: Build with Maven
        image: maven:3.8-openjdk-17
        caches:
          - maven
        script:
          - mvn -B package --file pom.xml
        artifacts:
          - target/*.jar

definitions:
  caches:
    maven: ~/.m2/repository