version: '3.9'

services:
  backend:
    container_name: dotnet-container
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - database  

  database:
    container_name: postgres-container
    image: postgres:latest
    env_file:
      - .envdocker    
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: