pipelines:
  branches:
    main:
      - step:
          name: Build
          services:
            - docker
          script:
            - export DOCKER_TAG=${BITBUCKET_COMMIT:0:7}
            - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
            - docker push $DOCKER_IMAGE:$DOCKER_TAG
            - echo "DOCKER_TAG=$DOCKER_TAG" >> variables.env
          artifacts:
            - variables.env
            
      - step:
          name: Deploy
          image: ubuntu:22.04
          deployment: production
          script:
            - apt update && apt install -y git
            - source variables.env
            - git clone $K8S_REPO k8s-manifests 
            - cd k8s-manifests
            - git config user.name "Bitbucket Pipeline"
            - git config user.email "pipeline@bitbucket.org"
            - |
              awk -v image="$DOCKER_IMAGE:$DOCKER_TAG" '
                /image:/ {$0 = "        image: " image}
                {print}
              ' app.yml > temp.yml && mv temp.yml app.yml
            - |
              if [[ -n $(git status -s) ]]; then
                echo "Changes detected. Committing and pushing..."
                git add .
                git commit -m "Update image tag to ${DOCKER_TAG}"
                git push origin main
              else
                echo "No changes detected in Kubernetes manifests."
              fi