version: '3.9'

services:
  backend:
    container_name: django-container
    image: gerrome/recipeapp-django
   # build: .
    ports:
      - "8000:8000"
    depends_on:
      - database  

  database:
    container_name: postgres-container
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=recipe
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: