version: '3'
services:
  nagios:
    image: jasonrivers/nagios:latest
    ports:
      - "8080:80"
    volumes:
      - ./config:/opt/nagios/etc
      - ./plugins:/opt/Custom-Nagios-Plugins
    environment:
      - NAGIOS_TIMEZONE=UTC
    restart: always