name: Snyk Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  snyk-code-scan:
    name: Snyk Source Code Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Snyk CLI
        uses: snyk/actions/setup@master

      - name: Snyk Auth
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
        
      - name: Run Snyk to check for code vulnerabilities
        run: |
          snyk code test --severity-threshold=high --sarif-file-output=snyk-code-results.sarif || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      - name: Upload code scan results as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snyk-code-scan-results
          path: snyk-code-results.sarif
          retention-days: 7


  snyk-docker-scan:
    name: Snyk Docker Image Scan
    runs-on: ubuntu-latest
    needs: snyk-code-scan
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Build Docker image
        run: docker build -t my-app:${{ github.sha }} .
        
      - name: Setup Snyk CLI
        uses: snyk/actions/setup@master
        
      - name: Snyk Auth
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
        
      - name: Run Snyk to check Docker image for vulnerabilities
        run: |
          snyk container test my-app:${{ github.sha }} --file=Dockerfile --severity-threshold=high --json-file-output=snyk-container-results.json || true
          snyk container test my-app:${{ github.sha }} --file=Dockerfile --severity-threshold=high --sarif-file-output=snyk-container-results.sarif || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      - name: Upload container scan results as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snyk-container-scan-results
          path: |
            snyk-container-results.sarif
            snyk-container-results.json
          retention-days: 7