pipelines:
  branches:
    main:
      - step:
          name: Test
          script:
            - pipe: sonarsource/sonarqube-scan:1.0.0
              variables:
                SONAR_HOST_URL: ${SONAR_HOST_URL}
                SONAR_TOKEN: ${SONAR_TOKEN}
                SONAR_PROJECT_KEY: ${PROJECT_KEY}
                EXTRA_ARGS: -Dsonar.projectKey=${PROJECT_KEY}

      - step:
          name: Build
          services:
            - docker
          script:
            - export DOCKER_TAG=${BITBUCKET_COMMIT:0:7}
            - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
            - docker push $DOCKER_IMAGE:$DOCKER_TAG
            - echo "DOCKER_TAG=$DOCKER_TAG" >> variables.env
          artifacts:
            - variables.env
            
      - step:
          name: Deploy
          deployment: production
          script:
            - source variables.env
            - pipe: atlassian/ssh-run:0.4.0
              variables:
                SSH_USER: $USER
                SERVER: $HOST
                COMMAND: | 
                  docker pull $DOCKER_IMAGE:$DOCKER_TAG
                  docker run -p 5000:80 -d --name myapp $DOCKER_IMAGE:$DOCKER_TAG