version: '3'

services:
  bamboo-server:
    image: atlassian/bamboo-server
    container_name: bamboo-server
    user: root
    ports:
      - 54663:54663
      - 8085:8085
    volumes:
      - ./bamboohome:/var/atlassian/application-data/bamboo
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JVM_MINIMUM_MEMORY=1024m
      - JVM_MAXIMUM_MEMORY=2048m
    networks:
      - bamboo      

  postgres:
    image: postgres:13
    container_name: bamboo-postgres
    environment:
      - POSTGRES_DB=bamboo
      - POSTGRES_USER=bamboouser
      - POSTGRES_PASSWORD=bamboopassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bamboo      

  bamboo-agent:
    image: atlassian/bamboo-agent-base
    container_name: bamboo-agent
    privileged: true
    volumes:
      - bamboo_agent:/var/atlassian/application-data/bamboo
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - BAMBOO_SERVER_URL=http://bamboo-server:8085
      - SECURITY_TOKEN=258d1458958b6cf4297ba38b225a9ee304eaec99
    depends_on:
      - bamboo-server
    networks:
      - bamboo      


network:
  bamboo:

volumes:
  bamboo_agent_home:
  postgres_data: