stages:
  - build
  - deploy

variables:
  DOCKER_TAG: ${CI_COMMIT_SHORT_SHA}  

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind  
  before_script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  script:
    - docker build -t $DOCKER_IMAGE:${CI_COMMIT_SHORT_SHA} .
    - docker push $DOCKER_IMAGE:${CI_COMMIT_SHORT_SHA}
  only:
    - main

deploy:
  stage: deploy
  image: bitnami/git:latest
  script:
    - git clone https://${CI_USERNAME}:${CI_PASSWORD}@${K8S_MANIFEST_REPO} k8s-manifests
    - cd k8s-manifests
    - git config user.name "GitLab CI"
    - git config user.email "gitlab-ci@example.com"
    - git pull origin main
    - |
      awk -v image="${DOCKER_IMAGE}:${DOCKER_TAG}" '
        /image:/ {$0 = "        image: " image}
        {print}
      ' app.yml > temp.yml && mv temp.yml app.yml
    - |
      if [[ -n $(git status -s) ]]; then
        echo "Changes detected. Committing and pushing..."
        git add .
        git commit -m "Update image tag to ${DOCKER_TAG}"
        git push origin main
      else
        echo "No changes detected in Kubernetes manifests."
      fi
  only:
    - main