apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: laravel
spec:
  selector:
    matchLabels:
      app: laravel
  replicas: {{ .Values.laravel.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: laravel
    spec:
      initContainers:
      - name: check-mysql-ready
        image: mysql:8.0
        command: ['sh', '-c', 
          'until mysql -h mysql-service -u root -p${MYSQL_ROOT_PASSWORD} -e "SELECT 1"; 
          do echo waiting for mysql; sleep 2; done;']
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: root-password    
      containers: 
      - name: laravel-container
        image: {{ .Values.laravel.image }}:{{ .Values.laravel.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080    
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: {{ .Values.namespace }}
  labels:
    app: laravel
spec:
  type: ClusterIP
  selector:
    app: laravel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080