apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-4"
type: Opaque
data:
stringData:
  database: {{ .Values.mysql.database }}
  root-password: {{ .Values.mysql.password }} 
  