stages:
  - test

variables:
  DOCKER_TAG: $CI_COMMIT_SHA

testTrivy:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache curl
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
  script:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - trivy image --format json -o trivy-results.json $DOCKER_IMAGE:$DOCKER_TAG
    - trivy image --format table -o trivy-results.txt $DOCKER_IMAGE:$DOCKER_TAG
  artifacts:
    name: "trivy-scan-results"
    paths:
      - trivy-results.json
      - trivy-results.txt
    when: always
    expire_in: 1 week
  allow_failure: true