version: 2
plan:
  project-key: GER
  key: BUILD
  name: Docker-GKE-Workflow

stages:
  - Build-Docker:
      jobs:
        - Build-Docker-Image

# === BUILD DOCKER IMAGE JOB ===
Build-Docker-Image:
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |
            set -e
            
            DOCKERHUB_USERNAME=${bamboo.DOCKERHUB_USERNAME_SECRET}
            DOCKERHUB_PASSWORD=${bamboo.DOCKERHUB_PASSWORD}
            DOCKER_IMAGE=${bamboo.DOCKER_IMAGE_SECRET}

            # Get commit SHA for tagging
            COMMIT_SHA=${bamboo.repository.revision.number}
            
            echo "Logging into Docker Hub"
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            
            echo "Building Docker image"
            docker build -t $DOCKER_IMAGE:$COMMIT_SHA .
            
            echo "Pushing Docker image to registry"
            docker push $DOCKER_IMAGE:$COMMIT_SHA

---
version: 2

release-naming:
  next-version-name: release-1.1
  applies-to-branches: true
  auto-increment: true

environments:
  - deployment
# === DEPLOY TO GKE JOB ===
deployment:
  name: GKE-Deployment
  source-plan: GER-BUILD
  triggers: 
    - build-success  
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |
            set -e

            echo "Setting up environment variables..."
            GCP_PROJECT_ID="${bamboo.GCP_PROJECT_ID_SECRET}"
            GCP_CLIENT_ID="${bamboo.GCP_CLIENT_ID_SECRET}"
            GCP_REFRESH_TOKEN="${bamboo.GCP_REFRESH_TOKEN_SECRET}"
            GKE_CLUSTER_NAME="${bamboo.GKE_CLUSTER_NAME_SECRET}"
            GKE_CLUSTER_ZONE="${bamboo.GKE_CLUSTER_ZONE_SECRET}"            
            DOCKER_TAG="${bamboo.repository.revision.number}"
            DOCKER_IMAGE=${bamboo.DOCKER_IMAGE_SECRET}

            echo "Cleaning up previous container (if exists)"
            docker rm -f gcloud-deploy || true

            echo "Starting deployment container..."
            docker run -d --name gcloud-deploy ubuntu:22.04 tail -f /dev/null

            echo "Copying source files into container"
            docker cp "${bamboo.build.working.directory}" gcloud-deploy:/app

            echo "Installing dependencies and Google Cloud SDK..."
            docker exec gcloud-deploy sh -c "
              apt update && \\
              apt install -y apt-transport-https ca-certificates gnupg curl && \\
              curl https://packages.cloud.google.com/apt/doc/apt-key.gpg  | apt-key add - && \\
              echo 'deb https://packages.cloud.google.com/apt  cloud-sdk main' > /etc/apt/sources.list.d/google-cloud-sdk.list && \\
              apt update && \\
              apt install -y google-cloud-sdk google-cloud-sdk-gke-gcloud-auth-plugin kubectl git
            "

            echo "Authenticating to GCP and Authenticate with GKE..."
            docker exec gcloud-deploy sh -c "
              gcloud auth activate-refresh-token \"${GCP_CLIENT_ID}\" \"${GCP_REFRESH_TOKEN}\" && \\
              gcloud config set project \"${GCP_PROJECT_ID}\"
              gcloud container clusters get-credentials "${GKE_CLUSTER_NAME}" --zone "${GKE_CLUSTER_ZONE}" 
            "

            echo "Confirm Authentication..."
            docker exec gcloud-deploy sh -c "
              kubectl get nodes
            "

            echo "Deploying K8s Manifests..."
            docker exec gcloud-deploy sh -c '
              cd /app/k8s &&
              sed -i "s|^\( *image: *\).*$|\1'"${DOCKER_IMAGE}:${DOCKER_TAG}"'|" app.yml &&
              kubectl apply -f .
            '

            echo "Cleaning up container"
            docker stop gcloud-deploy
            docker rm gcloud-deploy