version: '3.9'

services:
  frontend:
    container_name: react-app
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - frontend_network

  backend:
    container_name: django-app
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - backend_network
      - frontend_network      

  database:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend_network      

volumes:
  db-data:

networks:
  frontend_network:
  backend_network: