version: '3.9'

services:
  backend:
    container_name: dotnet-container
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - database  

  database:
    container_name: postgres-container
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=recipe
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: