pipelines:
  branches:
    main:
      - step:
          name: Build
          services:
            - docker
          script:
            - export DOCKER_TAG=${BITBUCKET_COMMIT}
            - export GCP_REGION=us-central1
            - export SERVICE_NAME=my-application
            - export GCP_REPOSITORY=container-images
            - export DOCKER_IMAGE=${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${GCP_REPOSITORY}/${SERVICE_NAME}
            - apt-get update
            - apt-get install -y apt-transport-https ca-certificates gnupg curl
            - echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
            - apt-get update
            - apt-get install -y google-cloud-sdk
            - gcloud auth activate-refresh-token "$GCP_CLIENT_ID" "$GCP_REFRESH_TOKEN"
            - gcloud config set project "$GCP_PROJECT_ID"
            - gcloud auth configure-docker ${GCP_REGION}-docker.pkg.dev --quiet
            - gcloud artifacts repositories describe ${GCP_REPOSITORY} --location=${GCP_REGION} || gcloud artifacts repositories create ${GCP_REPOSITORY} --repository-format=docker --location=${GCP_REGION}
            - docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} .
            - docker tag ${DOCKER_IMAGE}:${DOCKER_TAG} ${DOCKER_IMAGE}:latest
            - docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
            - docker push ${DOCKER_IMAGE}:latest
            - echo "Successfully pushed ${DOCKER_IMAGE}:${DOCKER_TAG}"
            - echo "DOCKER_TAG=${DOCKER_TAG}" >> variables.env
            - echo "GCP_REGION=${GCP_REGION}" >> variables.env
            - echo "SERVICE_NAME=${SERVICE_NAME}" >> variables.env
            - echo "GCP_REPOSITORY=${GCP_REPOSITORY}" >> variables.env
            - echo "DOCKER_IMAGE=${DOCKER_IMAGE}" >> variables.env
          artifacts:
            - variables.env
            
      - step:
          name: Deploy
          script:
            - source variables.env
            - apt-get update
            - apt-get install -y apt-transport-https ca-certificates gnupg curl
            - echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
            - apt-get update
            - apt-get install -y google-cloud-sdk
            - gcloud auth activate-refresh-token "$GCP_CLIENT_ID" "$GCP_REFRESH_TOKEN"
            - gcloud config set project "$GCP_PROJECT_ID"
            - gcloud run deploy ${SERVICE_NAME} --image=${DOCKER_IMAGE}:${DOCKER_TAG} --region=${GCP_REGION} --platform=managed --memory=512Mi --cpu=1 --min-instances=0 --max-instances=10 --concurrency=80 --timeout=300s --port=80 --quiet
            - SERVICE_URL=$(gcloud run services describe ${SERVICE_NAME} --region=${GCP_REGION} --format='value(status.url)')