apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: django-postgres
  labels:
    app: django
spec:
  selector:
    matchLabels:
      app: django
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: django
    spec:
      initContainers:
      - name: check-postgres-ready
        image: postgres:15-alpine
        command: ['sh', '-c', 
          'until pg_isready -h postgres-service -p 5432; 
          do echo waiting for postgres; sleep 2; done;']
      containers: 
      - name: django-container
        image: gerrome/recipeapp-django
        imagePullPolicy: Always
        ports:
        - containerPort: 8000      
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: django-postgres
  labels:
    app: django
spec:
  type: ClusterIP
  selector:
    app: django
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 8000