stages:
  - build

build:
  stage: build
  image: openjdk:17
  before_script:
    - apt update && apt install -y ant
  script:
    - ant -noinput -buildfile build.xml
  artifacts:
    paths:
      - dist/*.jar