name: Docker Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
  DOCKER_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      DOCKER_CONTAINER_NAME: react-app
      CONTAINER_PORT: 3000
      HOST_PORT: 80
    steps:
    - name: Deploy to remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        envs: DOCKER_IMAGE,DOCKER_TAG,DOCKER_CONTAINER_NAME,CONTAINER_PORT,HOST_PORT
        script: |
          # Login to DockerHub
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          
          echo "Cleaning up old containers..."
          docker ps -q --filter name=$DOCKER_CONTAINER_NAME | xargs -r docker stop
          docker ps -aq --filter name=$DOCKER_CONTAINER_NAME | xargs -r docker rm
          
          echo "Pulling new image: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}"
          docker pull ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
          
          echo "Running new container..."
          docker run -d \
            --name $DOCKER_CONTAINER_NAME \
            -p $CONTAINER_PORT:$HOST_PORT \
            ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
          
          echo "Verifying deployment..."
          docker ps | grep $DOCKER_CONTAINER_NAME
          
          echo "Logging out of Docker Hub..."
          docker logout