version: '3.9'

services:
  backend:
    container_name: django-container
    image: gerrome/recipeapp-django
   # build: .
    ports:
      - "8000:8000"
    depends_on:
      - database  

  database:
    container_name: postgres-container
    image: postgres:latest
    env_file:
      - .envdocker    
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: