---
- name: Deploying Real Estate Django App
  hosts: all
  remote_user: ubuntu
  become: yes

  tasks:

  - name: Update Apt Repository
    apt:
      update_cache: yes

  - name: Install required system Packages
    apt:
      name:
       - git
       - nginx
       - python3
       - python3-pip
       - postgresql
      state: present
      update_cache: yes

  - name: Install virtualenv
    pip:
     name: virtualenv

  - name: Change Directory
    shell: 
      cmd: python3 -m virtualenv realvenv
      chdir: /home/ubuntu/Real-Estate-Django-Web-App

  - name: Install python requirements in (virtualenv)
    pip:
      requirements: /home/ubuntu/Real-Estate-Django-Web-App/requirements.txt
      virtualenv: /home/ubuntu/Real-Estate-Django-Web-App/realvenv

  - name: clone git http repo
    shell: "git clone https://github.com/Paulanisiobi/Real-Estate-Django-Web-App.git"

  - name: Set up PostgreSQL database
    become_user: postgres
    become_method: sudo
    command: |
      psql -c "CREATE DATABASE real_estate;"
      psql -c "CREATE USER pks WITH PASSWORD 'abc123!';"
      psql -c "GRANT ALL PRIVILEGES ON DATABASE real_estate TO pks;"
      
  - name: Activate virtual environment and install requirements
    command: |
      source /home/ubuntu/Real-Estate-Django-Web-App/realvenv/bin/activate
      pip install -r /home/ubuntu/Real-Estate-Django-Web-App/requirements.txt
    args:
      chdir: /home/ubuntu/Real-Estate-Django-Web-App

  - name: Update Django settings
    lineinfile:
        path: /home/ubuntu/Real-Estate-Django-Web-App/realestate/settings.py
        regexp: '^ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'

  - name: Migrate database
    command: python3 manage.py migrate
    args:
      chdir: /home/ubuntu/Real-Estate-Django-Web-App

  - name: Start Django service
    command: python3 manage.py runserver 
    args:
      chdir: /home/ubuntu/Real-Estate-Django-Web-App

  - name: Create wsgi.py file
    copy:
      content: |
        import os
        from django.core.wsgi import get_wsgi_application
        os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'realestate.settings')
        application = get_wsgi_application()
      dest: /home/ubuntu/Real-Estate-Django-Web-App/wsgi.py
      



