apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-4"
type: Opaque
stringData:
  root-username: {{ .Values.mongodb.username }}
  root-password: {{ .Values.mongodb.password }}