stages:
  - test
  - build

variables:
  DOCKER_TAG: $CI_COMMIT_SHA

testScan:
  stage: test
  image: aquasec/trivy:latest
  script:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - trivy image --format template --template "@contrib/sarif.tpl" -o trivy-results.sarif --severity HIGH,CRITICAL $DOCKER_IMAGE:$DOCKER_TAG
  artifacts:
    paths:
      - trivy-results.sarif

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  script:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
  only:
    - main