apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: java
spec:
  selector:
    matchLabels:
      app: java
  replicas: {{ .Values.java.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: java
    spec:
      initContainers:
      - name: check-mysql-ready
        image: mysql:8.0
        command: ['sh', '-c', 
          'until mysql -h mysql-service -u root -p${MYSQL_ROOT_PASSWORD} -e "SELECT 1"; 
          do echo waiting for mysql; sleep 2; done;']
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: root-password
      containers: 
      - name: java-container
        image: {{ .Values.java.image }}:{{ .Values.java.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-service
  namespace: {{ .Values.namespace }}
  labels:
    app: java
spec:
  type: ClusterIP
  selector:
    app: java
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080