route:
  group_by: ['alertname', 'severity']
  group_wait: 3s
  group_interval: 10s
  repeat_interval: 5m
  receiver: 'alertMail'

receivers:
  - name: 'alertMail'
    email_configs:
      - send_resolved: true
        to: 'vsifah@gmail.com'
        from: 'alert@sieger.com.ng'
        smarthost: 'standard15.doveserver.com:587'
        auth_username: 'alert@sieger.com.ng'
        auth_password: ''
        require_tls: false
    slack_configs:
      - send_resolved: true
        api_url: 'slackwebhook-url'
        channel: '#alerts'
        icon_emoji: ':warning:'
        title: '{{ .GroupLabels.alertname }}'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Severity:* {{ .Labels.severity }}
            *Start:* {{ .StartsAt }}
          {{ end }}
