apiVersion: v1
kind: Secret
metadata:
  name: github-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/GerromeSieger/Jenkin-test.git
  username: GerromeSieger
  password: <githubtoken>